version: '2.3'
services:

  # tag:build
  build-frontend:
    build:
      context: .
      dockerfile: Dockerfile.builder.frontend

  build-linux-amd64:
    image: defreitas/dns-proxy-server:2.19.5
    build:
      context: .
      dockerfile: Dockerfile

  # end:build

  # tag:development

  # end:development

  prod-build-image-dps-arm7x86:
    build:
      context: .
      dockerfile: Dockerfile.arm7x86
    image: defreitas/dns-proxy-server:2.19.5-arm7x86

  prod-build-image-dps-arm8x64:
    build:
      context: .
      dockerfile: Dockerfile.arm8x64
    image: defreitas/dns-proxy-server:2.19.5-arm8x64

networks:
  dps:
  dps_bridge:
    driver: bridge


#  docker run --rm -t docker.io/library/dns-proxy-server-build-default bash
