version: '2.3'
services:
  deploy:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    command: /bin/builder.bash deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
