version: '3'
services:

  # tag:build
  build-frontend:
    build:
      context: .
      dockerfile: Dockerfile.builder.frontend
    image: defreitas/dns-proxy-server-build-frontend:${VERSION:-snapshot}

  build-linux-amd64:
    image: defreitas/dns-proxy-server-build:${VERSION:-snapshot}-amd64
    build:
      context: .
      dockerfile: Dockerfile.builder.linux-amd64

  build-linux-aarch64:
    image: defreitas/dns-proxy-server-build:${VERSION:-snapshot}-aarch64
    build:
      context: .
      dockerfile: Dockerfile.builder.linux-aarch64
    platform: linux/arm64/v8

  # end:build

  # tag:image
  image-linux-amd64:
    image: defreitas/dns-proxy-server:${VERSION:-snapshot}
    build:
      context: .
      dockerfile: Dockerfile

  image-linux-aarch64:
    image: defreitas/dns-proxy-server:${VERSION:-snapshot}-aarch64
    build:
      context: .
      dockerfile: Dockerfile.aarch64

  # end:image

  # tag:development

  # end:development

  prod-build-image-dps-arm7x86:
    build:
      context: .
      dockerfile: Dockerfile.arm7x86
    image: defreitas/dns-proxy-server:${VERSION:-snapshot}-arm7x86

  prod-build-image-dps-arm8x64:
    build:
      context: .
      dockerfile: Dockerfile.arm8x64
    image: defreitas/dns-proxy-server:${VERSION:-snapshot}-arm8x64
