name: CD
#on:
#  push:
#    branches:
#      - master

on:
  pull_request:

permissions:
  contents: write

env:
  CURRENT_BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Explain
        run: |
          echo "Bump version, build, generate github release, push docker images and the docs"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Environment
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Deploy
        run: ./builder.bash deploy
        env:
          # github token to deploy the binary
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docs Generate
        id: docs_generate
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - name: Build docs
        run: |
          ./builder.bash docs /tmp/build &&\
          echo "VERSION=$(cat VERSION | awk -F '.' '{ print $1"."$2}')" >> "${GITHUB_OUTPUT}"

      - name: Docs Deploy - Latest
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/latest
          destination_dir: latest
          keep_files: true
          commit_message: Releasing the docs for latest

      - name: Docs Deploy - Minor
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/docs/${{ steps.docs_generate.outputs.VERSION }}'
          destination_dir: '${{ steps.docs_generate.outputs.VERSION }}'
          keep_files: true
          commit_message: 'Releasing the docs: ${{ steps.docs_generate.outputs.VERSION }}'

